In [1]:
import cv2

In [2]:
img =cv2.imread("D:/zzz/test.jpg")

In [3]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
print(img)

[[[ 71 112 121]
  [ 70 111 120]
  [ 63 104 113]
  ...
  [ 51  78  75]
  [ 53  80  77]
  [ 56  83  80]]

 [[ 69 110 119]
  [ 70 111 120]
  [ 76 117 126]
  ...
  [ 61  88  85]
  [ 59  86  83]
  [ 55  82  79]]

 [[ 66 107 116]
  [ 69 110 119]
  [ 79 120 129]
  ...
  [ 45  72  68]
  [ 53  80  76]
  [ 55  82  78]]

 ...

 [[ 16  42  66]
  [ 22  49  70]
  [ 21  48  68]
  ...
  [ 65 101 101]
  [ 69 107 107]
  [ 71 109 109]]

 [[ 14  40  64]
  [ 30  57  78]
  [ 44  71  91]
  ...
  [ 64 101  99]
  [ 75 113 113]
  [ 79 117 117]]

 [[ 20  46  70]
  [ 38  65  86]
  [ 68  95 115]
  ...
  [ 58  95  93]
  [ 63 101 101]
  [ 60  98  98]]]


In [5]:
print(img.ndim)
print(img.shape)

3
(512, 512, 3)


In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [12]:
import numpy as np
new_img=img[250:450,150:450]
cv2.imshow("img2",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
img2 =cv2.imread("D:/Python programming/numpy & pandas/f16_nobg_1jet.jpg")

In [16]:
print(img2)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
