In [140]:
from PIL import Image

In [141]:
img = Image.open("D:/Python programming/numpy & pandas/f16_nobg_1jet.jpg")

In [142]:
img.show()

In [143]:
import numpy as np
img_mat= np.array(img)

In [144]:
img.size

(1202, 579)

In [145]:
print(img_mat.shape)

(579, 1202, 3)


In [146]:
img_mat[2].size

3606

In [147]:
img_mat[1].shape

(1202, 3)

In [148]:
recreate= img_mat[100]

In [149]:
recreate.shape

(1202, 3)

In [150]:
recreate.dtype

dtype('uint8')

In [151]:
recreate_img =Image.fromarray(recreate)

In [191]:
recreate_img.show()

getting a specific pixels with color in image

In [153]:
print(recreate)
print(recreate.sum())

[[255 255 255]
 [255 255 255]
 [255 255 255]
 ...
 [255 255 255]
 [255 255 255]
 [255 255 255]]
850803


In [154]:
recreate= img_mat[100]
new_pixel = []
for j in range(len(recreate)):
    if recreate[j].sum() != 765:
        print(recreate[j])
        new_pixel.append(recreate[j])

[255 254 255]
[252 250 251]
[244 242 243]
[236 235 233]
[226 225 221]
[217 213 210]
[204 201 196]
[196 193 188]
[189 186 179]
[179 176 169]
[175 170 164]
[171 164 158]
[168 161 155]
[165 158 150]
[156 149 141]
[145 138 130]
[136 127 120]
[128 119 110]
[127 118 109]
[123 114 107]
[119 108 102]
[116 105  99]
[115 104 100]
[114 103  99]
[112 101  97]
[110  99  95]
[117 104  96]
[117 104  96]
[117 104  96]
[115 102  94]
[112  97  90]
[109  94  87]
[108  94  85]
[108  94  85]
[106  92  83]
[105  91  82]
[104  90  81]
[98 84 75]
[93 79 70]
[97 80 72]
[96 79 71]
[88 71 63]
[82 67 60]
[81 66 59]
[79 64 57]
[75 60 53]
[72 57 50]
[69 54 47]
[67 52 45]
[67 52 45]
[66 51 44]
[58 43 36]
[56 41 34]
[54 39 32]
[49 34 27]
[51 36 29]
[55 40 33]
[52 37 30]
[48 33 26]
[49 34 27]
[49 34 27]
[47 32 25]
[46 31 24]
[46 31 24]
[46 31 24]
[45 30 23]
[42 27 20]
[42 27 20]
[41 26 19]
[41 26 21]
[39 24 19]
[38 23 18]
[39 24 19]
[41 26 21]
[42 27 22]
[42 27 22]
[36 21 16]
[39 24 19]
[40 27 21]
[39 26 20]
[42 29 23

In [155]:
new_pixel=np.array(new_pixel,dtype='uint8')
print(new_pixel)

[[255 254 255]
 [252 250 251]
 [244 242 243]
 [236 235 233]
 [226 225 221]
 [217 213 210]
 [204 201 196]
 [196 193 188]
 [189 186 179]
 [179 176 169]
 [175 170 164]
 [171 164 158]
 [168 161 155]
 [165 158 150]
 [156 149 141]
 [145 138 130]
 [136 127 120]
 [128 119 110]
 [127 118 109]
 [123 114 107]
 [119 108 102]
 [116 105  99]
 [115 104 100]
 [114 103  99]
 [112 101  97]
 [110  99  95]
 [117 104  96]
 [117 104  96]
 [117 104  96]
 [115 102  94]
 [112  97  90]
 [109  94  87]
 [108  94  85]
 [108  94  85]
 [106  92  83]
 [105  91  82]
 [104  90  81]
 [ 98  84  75]
 [ 93  79  70]
 [ 97  80  72]
 [ 96  79  71]
 [ 88  71  63]
 [ 82  67  60]
 [ 81  66  59]
 [ 79  64  57]
 [ 75  60  53]
 [ 72  57  50]
 [ 69  54  47]
 [ 67  52  45]
 [ 67  52  45]
 [ 66  51  44]
 [ 58  43  36]
 [ 56  41  34]
 [ 54  39  32]
 [ 49  34  27]
 [ 51  36  29]
 [ 55  40  33]
 [ 52  37  30]
 [ 48  33  26]
 [ 49  34  27]
 [ 49  34  27]
 [ 47  32  25]
 [ 46  31  24]
 [ 46  31  24]
 [ 46  31  24]
 [ 45  30  23]
 [ 42  27 

In [156]:
 new_pixel.shape

(170, 3)

In [157]:
recreate.shape

(1202, 3)

In [158]:
pixel_img=Image.fromarray(new_pixel)

In [190]:
pixel_img.show()

In [160]:
new_img = []
for i in range(len(img_mat)):
    if img_mat[i].sum() != 919530:   
        new_img.append(img_mat[i])

In [161]:
new_img=np.array(new_img)

In [162]:
new_img.shape
print(new_img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [163]:
new_image=Image.fromarray(new_img)

In [189]:
new_image.show()

creating_image_after cleaning the background and recreating using padding and with pixels 

In [165]:
new_img2 = []
for i in range(len(img_mat)):
    if img_mat[i].sum() != 919530:
        recreate= img_mat[i]
        new_pixel = []
        for j in range(len(recreate)):
            if recreate[j].sum() != 765:
#                 print(recreate[j])
                new_pixel.append(recreate[j])
        if new_pixel !=[]:
            new_pixel=np.array(new_pixel,dtype='uint8')
            print(new_pixel)
            new_img2.append(new_pixel)
#             new_img2=np.concatenate(new_img2,new_pixel)

[[255 255 253]
 [255 255 253]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]]
[[255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]]
[[255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [255 254 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 25

[[254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 255 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [254 254 255]
 [252 252 254]
 [250 250 252]
 [249 249 251]
 [247 247 247]
 [246 246 246]
 [245 245 245]
 [243 243 241]
 [239 239 237]
 [236 236 234]
 [234 233 231]
 [232 231 229]
 [226 225 223]
 [224 223 221]
 [221 217 216]
 [218 214 211]
 [215 211 208]
 [213 209 206]
 [211 207 204]
 [210 206 203]
 [199 199 191]
 [197 197 189]
 [197 194 187]
 [194 191 186]
 [191 186 182]
 [188 183 179]
 [188 180 177]
 [186 178 176]
 [182 174 172]
 [181 173 171]
 [178 170 168]
 [176 168 166]
 [174 165 166]
 [172 163 164]
 [170 161 162]
 [169 160 161]
 [169 161 158]
 [169 161 158]
 [169 161 158]
 [167 159 

[[254 254 255]
 [254 252 253]
 [248 246 247]
 [243 241 242]
 [237 236 234]
 [229 228 224]
 [220 219 215]
 [214 213 208]
 [209 208 203]
 [201 200 195]
 [190 187 182]
 [186 183 178]
 [187 184 179]
 [189 186 181]
 [186 181 175]
 [181 176 170]
 [175 170 164]
 [169 164 158]
 [171 164 158]
 [169 162 156]
 [166 159 153]
 [164 155 150]
 [161 152 147]
 [159 149 147]
 [157 147 145]
 [155 145 143]
 [153 142 136]
 [153 142 136]
 [151 140 134]
 [147 136 130]
 [143 132 126]
 [139 128 122]
 [137 126 120]
 [136 126 117]
 [137 124 116]
 [132 119 111]
 [129 116 108]
 [127 114 106]
 [119 106  98]
 [114 101  93]
 [111  98  90]
 [107  94  86]
 [101  86  79]
 [ 98  83  76]
 [ 94  79  72]
 [ 89  74  67]
 [ 84  69  62]
 [ 80  65  58]
 [ 77  62  55]
 [ 75  60  53]
 [ 69  54  47]
 [ 65  50  43]
 [ 67  52  45]
 [ 69  54  47]
 [ 64  49  42]
 [ 63  48  41]
 [ 62  47  40]
 [ 55  40  33]
 [ 59  45  36]
 [ 60  46  37]
 [ 57  43  34]
 [ 53  39  30]
 [ 51  37  28]
 [ 50  36  27]
 [ 48  33  26]
 [ 45  30  23]
 [ 42  27 

[[254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [254 254 254]
 [253 254 249]
 [252 252 250]
 [253 253 251]
 [251 251 249]
 [248 248 248]
 [249 249 249]
 [248 248 250]
 [241 241 243]
 [235 235 237]
 [211 211 213]
 [207 207 209]
 [202 202 204]
 [191 192 194]
 [161 163 162]
 [148 150 149]
 [155 157 156]
 [143 150 156]
 [150 155 161]
 [154 157 162]
 [157 158 162]
 [111 109 112]
 [ 86  82  83]
 [ 58  49  50]
 [ 43  31  31]
 [ 40  26  25]
 [ 45  30  27]
 [ 47  32  29]
 [ 47  32  27]
 [ 46  31  26]
 [ 46  31  26]
 [ 44  29  24]
 [ 41  26  21]
 [ 48  31  21]
 [ 48  31  21]
 [ 47  30  20]
 [ 44  27  17]
 [ 41  24  14]
 [ 41  24  16]
 [ 43  26  18]
 [ 44  30  21]
 [ 48  34  25]
 [ 42  28  19]
 [ 38  23  16]
 [ 38  23  16]
 [ 40  25  18]
 [ 41  28  20]
 [ 44  31  23]
 [ 48  35  27]
 [ 45  32  24]
 [ 49  36  28]
 [ 53  40  32]
 [ 54  41  33]
 [ 50  37  29]
 [ 48  35  27]
 [ 54  40  31]
 [ 60  46  37]
 [ 69  55  46]
 [ 62  48  39]
 [ 64  50 

[[254 254 254]
 [247 247 247]
 [235 235 235]
 ...
 [254 255 255]
 [254 255 255]
 [253 255 254]]
[[252 252 252]
 [254 254 254]
 [247 247 247]
 ...
 [254 255 255]
 [253 255 254]
 [253 255 254]]
[[254 254 254]
 [254 254 254]
 [254 254 254]
 ...
 [253 253 253]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [253 253 253]
 [254 254 254]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 254 254]
 [253 253 253]
 [254 254 254]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 254 254]
 [254 254 254]
 [250 250 250]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 254 254]
 [251 251 251]
 [245 245 245]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 254 254]
 [252 252 252]
 [248 248 248]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[252 252 252]
 [250 250 250]
 [244 244 244]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[253 253 253]
 [252 252 252]
 [248 248 248]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [253 253 253]
 [254 254 

[[254 255 255]
 [253 254 255]
 [252 254 253]
 ...
 [252 252 252]
 [253 253 253]
 [254 254 254]]
[[254 255 255]
 [254 255 255]
 [253 255 254]
 ...
 [254 254 254]
 [253 253 253]
 [254 254 254]]
[[253 254 255]
 [254 255 255]
 [254 255 255]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[250 254 253]
 [252 254 253]
 [254 255 255]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[252 255 255]
 [253 255 254]
 [253 255 254]
 ...
 [254 254 254]
 [253 253 253]
 [254 254 254]]
[[254 255 255]
 [254 255 255]
 [254 255 255]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 255 255]
 [254 255 255]
 [254 255 255]
 ...
 [255 254 255]
 [255 254 255]
 [255 254 255]]
[[254 255 255]
 [254 255 255]
 [253 255 254]
 ...
 [250 252 251]
 [252 254 253]
 [254 254 254]]
[[254 254 254]
 [253 253 253]
 [251 251 251]
 ...
 [253 255 254]
 [253 255 254]
 [254 254 254]]
[[254 254 254]
 [254 254 254]
 [254 254 254]
 ...
 [254 255 255]
 [254 255 255]
 [254 255 255]]
[[254 254 254]
 [254 254 254]
 [252 252 

[[251 251 251]
 [250 250 250]
 [249 249 249]
 ...
 [252 252 252]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [254 254 254]
 [253 253 253]
 ...
 [253 253 253]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [250 250 250]
 [246 246 246]
 ...
 [231 232 234]
 [241 243 242]
 [254 254 254]]
[[254 254 254]
 [254 254 254]
 [253 253 253]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [254 254 254]
 [254 254 254]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]
[[254 254 254]
 [249 249 249]
 [248 248 248]
 ...
 [241 241 241]
 [253 253 251]
 [255 255 253]]
[[254 254 254]
 [254 254 254]
 [254 254 254]
 ...
 [243 243 243]
 [254 254 252]
 [255 255 253]]
[[254 254 254]
 [254 254 254]
 [251 251 251]
 ...
 [244 244 244]
 [254 254 252]
 [255 255 253]]
[[254 254 254]
 [254 254 254]
 [253 255 254]
 ...
 [246 246 246]
 [253 253 251]
 [255 255 253]]
[[254 254 254]
 [254 254 254]
 [254 254 254]
 ...
 [249 249 247]
 [255 255 253]
 [255 255 253]]
[[255 254 255]
 [254 254 254]
 [254 254 

[[254 254 254]
 [250 250 248]
 [241 241 239]
 [232 232 230]
 [224 226 223]
 [213 215 212]
 [190 192 189]
 [161 156 152]
 [139 134 130]
 [120 115 111]
 [114 107 101]
 [108  99  92]
 [100  90  81]
 [ 91  81  72]
 [ 85  72  63]
 [ 75  61  50]
 [ 64  50  39]
 [ 63  49  36]
 [ 63  49  36]
 [ 65  49  36]
 [ 63  47  34]
 [ 55  39  26]
 [ 52  38  25]
 [ 61  45  30]
 [ 62  46  31]
 [ 61  45  30]
 [ 57  41  26]
 [ 54  38  23]
 [ 55  39  24]
 [ 60  44  29]
 [ 64  48  33]
 [ 62  46  31]
 [ 59  43  28]
 [ 65  49  34]
 [ 60  44  29]
 [ 53  37  22]
 [ 57  41  26]
 [ 63  47  32]
 [ 60  44  29]
 [ 52  40  26]
 [ 53  41  27]
 [ 60  48  34]
 [ 58  46  32]
 [ 54  42  28]
 [ 53  41  27]
 [ 51  39  25]
 [ 57  45  31]
 [ 52  40  26]
 [ 52  40  28]
 [ 54  42  30]
 [ 53  41  29]
 [ 48  36  24]
 [ 47  35  23]
 [ 48  36  24]
 [ 49  37  25]
 [ 47  37  28]
 [ 45  35  26]
 [ 42  32  23]
 [ 37  27  18]
 [ 34  24  15]
 [ 34  24  15]
 [ 36  25  19]
 [ 39  28  22]
 [ 38  27  21]
 [ 36  25  19]
 [ 33  22  18]
 [ 32  21 

[[255 255 253]
 [255 255 253]
 [254 254 254]
 [249 249 249]
 [241 241 241]
 [237 237 237]
 [231 231 231]
 [221 221 221]
 [201 201 201]
 [181 180 178]
 [162 158 157]
 [147 143 140]
 [135 130 127]
 [125 117 114]
 [108 100  97]
 [ 92  84  81]
 [ 78  69  60]
 [ 66  57  48]
 [ 53  44  35]
 [ 44  35  26]
 [ 40  31  22]
 [ 39  30  21]
 [ 40  30  21]
 [ 41  31  22]
 [ 37  27  18]
 [ 45  35  25]
 [ 55  45  35]
 [ 43  33  23]
 [ 39  29  19]
 [ 49  39  29]
 [ 50  37  28]
 [ 53  40  31]
 [ 56  44  30]
 [ 51  39  25]
 [ 54  40  27]
 [ 57  43  30]
 [ 56  42  29]
 [ 61  47  34]
 [ 62  48  35]
 [ 55  41  28]
 [ 57  43  30]
 [ 64  50  37]
 [ 64  48  33]
 [ 62  46  31]
 [ 58  42  27]
 [ 56  40  25]
 [ 66  50  35]
 [ 70  54  39]
 [ 58  42  29]
 [ 65  49  36]
 [ 68  52  39]
 [ 66  50  37]
 [ 65  49  36]
 [ 68  50  38]
 [ 67  49  37]
 [ 63  45  33]
 [ 65  47  35]
 [ 63  47  34]
 [ 63  47  34]
 [ 58  44  31]
 [ 53  39  26]
 [ 51  37  24]
 [ 57  45  31]
 [ 66  54  40]
 [ 57  45  33]
 [ 61  49  37]
 [ 64  50 

[[255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [255 255 253]
 [254 254 254]
 [254 254 254]
 [254 254 255]
 [254 254 255]
 [251 255 255]
 [248 252 253]
 [250 254 255]
 [248 252 255]
 [239 243 246]
 [239 240 244]
 [237 238 242]
 [228 227 232]
 [219 218 223]
 [217 215 220]
 [218 213 217]
 [206 202 203]
 [199 193 195]
 [198 192 192]
 [185 176 177]
 [169 161 159]
 [140 128 132]
 [128 116 118]
 [109  97  99]
 [ 88  76  78]
 [ 73  61  63]
 [ 65  53  53]
 [ 63  51  51]
 [ 64  52  52]
 [ 52  41  39]
 [ 42  31  29]
 [ 49  38  34]
 [ 61  50  46]
 [ 56  45  41]
 [ 50  39  33]
 [ 53  42  36]
 [ 56  45  39]
 [ 59  48  46]
 [ 65  54  52]
 [ 72  62  60]
 [ 79  69  67]
 [ 83  73  71]
 [ 89  79  77]
 [ 98  90  87]
 [108 100  97]
 [108 103  99]
 [115 110 106]
 [124 119 115]
 [130 127 122]
 [133 130 125]
 [136 133 128]
 [143 140 135]
 [151 148 143]
 [150 149 147]
 [150 149 147]
 [151 149 150]
 [156 154 155]
 [165 163 166]
 [172 172 174]
 [176 175 180]
 [178 177 

In [166]:
print(new_img2)

[array([[255, 255, 253],
       [255, 255, 253],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [255, 255, 253],
       [255, 255, 253],
       [255, 255, 253],
       [255, 255, 253],
       [255, 255, 253],
       [255, 255, 253]], dtype=uint8), array([[255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [255, 254, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],
       [254, 255, 255],


In [167]:
def pad_array_2d(arr, target_shape, padding_value=0):
    padded = np.full(target_shape, padding_value, dtype=arr.dtype)
    padded[:arr.shape[0], :arr.shape[1]] = arr
    return padded

# Find the maximum shape
max_rows = max(arr.shape[0] for arr in new_img2)
max_cols = max(arr.shape[1] for arr in new_img2)
target_shape = (max_rows, max_cols)

# Pad all arrays to the target shape
padded_new_img2 = [pad_array_2d(arr, target_shape) for arr in new_img2]

# Create a numpy array with uint8 type
array = np.array(padded_new_img2, dtype='uint8')


In [168]:
array

array([[[255, 255, 253],
        [255, 255, 253],
        [255, 254, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 254, 255],
        [255, 254, 255],
        [255, 254, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 254, 255],
        [255, 254, 255],
        [255, 254, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[254, 254, 254],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[254, 254, 254],
        [253, 253, 253],
        [252, 252, 252],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[254, 254, 254],
        [254, 254, 254],
        [253, 253, 253],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [169]:
img4=Image.fromarray(array)

In [170]:
img4.show()

getting specific image crop

In [171]:
img_wing=img_mat[300:700,100:400]

In [172]:
img_w=Image.fromarray(img_wing)

In [173]:
img_w.show()

flipping images

In [ ]:
fighter_jets = Image.open("D:/Python programming/numpy & pandas/f16_nobg.jpg")

In [ ]:
jet=np.array(fighter_jets)

In [177]:
fighter_jets=fighter_jets.transpose(Image.FLIP_LEFT_RIGHT)

In [178]:
fighter_jets.show()

In [183]:
flipped_jet_horizontal = np.flip(jet, axis=1)

In [184]:
jet_img=Image.fromarray(flipped_jet_horizontal)

In [185]:
jet_img.show()

In [186]:
flipped_jet_vertical = np.flip(jet, axis=0)

In [187]:
jet_img=Image.fromarray(flipped_jet_vertical)

In [188]:
jet_img.show()